export const BLOG_POST_REQUEST = 'BLOG_POST_REQUEST';
export const BLOG_POST_FAIL = 'BLOG_POST_FAIL';
export const BLOG_POST_SUCCESS = 'BLOG_POST_SUCCESS';

export const BLOG_HOME_REQUEST = 'BLOG_HOME_REQUEST';
export const BLOG_HOME_SUCCESS = 'BLOG_HOME_SUCCESS';
export const BLOG_HOME_FAIL = 'BLOG_HOME_FAIL';

export const BLOG_TRENDING_REQUEST = 'BLOG_TRENDING_REQUEST';
export const BLOG_TRENDING_SUCCESS = 'BLOG_TRENDING_SUCCESS';
export const BLOG_TRENDING_FAIL = 'BLOG_TRENDING_FAIL';

export const BLOG_GET_REQUEST = 'BLOG_GET_REQUEST';
export const BLOG_GET_SUCCESS = 'BLOG_GET_SUCCESS';
export const BLOG_GET_FAIL = 'BLOG_GET_FAIL';

export const CLEAR_BLOG_ERROR = 'CLEAR_BLOG_ERROR';
